#!/usr/bin/env python3
"""Regenerate the SNAPSHOT data block in uc/index.html from a JSON export of the
Artifact's database (data/users/me/fund/{shareholders,products,entries,dividends}
collections plus the root doc's fxRates).

Usage:
    python3 uc/sync_snapshot.py <data.json> [--stamp "YYYY-MM-DD HH:MM UTC"]

Only the block between the SNAPSHOT-DATA-BEGIN / SNAPSHOT-DATA-END markers is
touched; everything else in uc/index.html (styles, render logic, read-only
shell) is left untouched. Does not commit or push anything.
"""
import argparse
import json
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
INDEX_HTML = REPO_ROOT / "uc" / "index.html"

BEGIN_MARKER = "/* SNAPSHOT-DATA-BEGIN"
END_MARKER = "/* SNAPSHOT-DATA-END */"

REQUIRED_KEYS = ["fxRates", "shareholders", "products", "entries", "dividends"]


def compact_json(obj):
    return json.dumps(obj, ensure_ascii=False, separators=(",", ":"))


def build_block(data, stamp):
    lines = [
        f"{BEGIN_MARKER} — generated by uc/sync_snapshot.py from the artifact's database; do not hand-edit */",
        f"const SNAPSHOT_AT = '{stamp}';",
        "const SNAPSHOT = {",
        f"  fxRates: {compact_json(data['fxRates'])},",
        "  shareholders: [",
    ]
    lines.append(",\n".join("    " + compact_json(s) for s in data["shareholders"]))
    lines.append("  ],")
    lines.append("  products: [")
    lines.append(",\n".join("    " + compact_json(p) for p in data["products"]))
    lines.append("  ],")
    lines.append("  entries: [")
    lines.append(",\n".join("    " + compact_json(e) for e in data["entries"]))
    lines.append("  ],")
    lines.append("  dividends: [")
    lines.append(",\n".join("    " + compact_json(d) for d in data["dividends"]))
    lines.append("  ]")
    lines.append("};")
    lines.append(END_MARKER)
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("data_json", help="Path to a JSON file with fxRates/shareholders/products/entries/dividends")
    ap.add_argument("--stamp", default=None, help="Snapshot timestamp label; defaults to now (UTC)")
    args = ap.parse_args()

    data = json.loads(Path(args.data_json).read_text(encoding="utf-8"))
    missing = [k for k in REQUIRED_KEYS if k not in data]
    if missing:
        sys.exit(f"data JSON missing required keys: {missing}")
    if not isinstance(data["shareholders"], list) or not isinstance(data["products"], list):
        sys.exit("shareholders/products must be arrays")

    stamp = args.stamp or datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    html = INDEX_HTML.read_text(encoding="utf-8")
    begin_idx = html.find(BEGIN_MARKER)
    end_idx = html.find(END_MARKER)
    if begin_idx == -1 or end_idx == -1:
        sys.exit("SNAPSHOT-DATA markers not found in uc/index.html — has the template changed?")
    end_idx += len(END_MARKER)

    new_block = build_block(data, stamp)
    new_html = html[:begin_idx] + new_block + html[end_idx:]
    INDEX_HTML.write_text(new_html, encoding="utf-8")
    print(f"uc/index.html updated (snapshot stamp: {stamp})")


if __name__ == "__main__":
    main()
